extends RefCounted

const DEFAULT_WORLD_SCALE := 6.0
const BASE_WORLD_RECT := Rect2(-1680, -1040, 3360, 2080)
const WORLD_RECT := Rect2(BASE_WORLD_RECT.position * DEFAULT_WORLD_SCALE, BASE_WORLD_RECT.size * DEFAULT_WORLD_SCALE)
const DEFAULT_SEED := 123456

const MAP_SAMPLE_WIDTH := 192
const MAP_SAMPLE_HEIGHT := 128

const ISLAND_RADIUS_X_RATIO := 0.82
const ISLAND_RADIUS_Y_RATIO := 0.74
const ISLAND_EDGE_FALLOFF_POWER := 1.45

const HEIGHT_NOISE_FREQUENCY := 0.004
const MOISTURE_NOISE_FREQUENCY := 0.005
const BIOME_NOISE_FREQUENCY := 0.003
const DANGER_NOISE_FREQUENCY := 0.0035

const DEEP_OCEAN_THRESHOLD := -0.35
const SHALLOW_WATER_THRESHOLD := -0.12
const SHORE_THRESHOLD := 0.02
const HIGHLAND_THRESHOLD := 0.58

const TARGET_POND_COUNT_MIN := 4
const TARGET_POND_COUNT_MAX := 7
const TARGET_HILL_COUNT_MIN := 5
const TARGET_HILL_COUNT_MAX := 9
const TARGET_LANDMARK_COUNT_MIN := 9
const TARGET_LANDMARK_COUNT_MAX := 14

const START_SAFE_RADIUS := 900.0
const LANDMARK_MIN_DISTANCE := 700.0
const POND_MIN_DISTANCE := 900.0
const HILL_MIN_DISTANCE := 850.0

const RESOURCE_DENSITY_MULTIPLIER := 1.0
const DECORATIVE_VEGETATION_DENSITY_MULTIPLIER := 1.0
const CREATURE_SPAWN_ZONE_COUNT := 32
