extends RefCounted
class_name GameBalance

# Crafting costs are wired into crafting in the next task.
const CRAFTING_COSTS := {
	"campfire": {"wood": 3, "stone": 2},
	"spear": {"wood": 2, "stone": 1, "fiber": 1},
	"torch": {"wood": 1, "fiber": 1},
	"cooked_meat": {"meat": 1},
	"basic_trap": {"wood": 2, "fiber": 2},
	"trap": {"wood": 2, "fiber": 2}
}

const TORCH_DURATION_SECONDS := 45.0
const TORCH_SAFE_RADIUS := 96.0
const TORCH_DETECTION_RANGE_MULTIPLIER := 0.65
const TORCH_AGGRESSION_MULTIPLIER := 0.7
const TORCH_CLOSE_CHASE_RANGE_MULTIPLIER := 0.65
const TORCH_ATTACK_COOLDOWN_MULTIPLIER := 1.5
const TORCH_FLEE_SPEED_MULTIPLIER := 0.85
const TORCH_LIGHT_RADIUS := 105.0
const TORCH_LIGHT_INTENSITY := 0.7

const CAMPFIRE_SAFE_RADIUS := 150.0
const CAMPFIRE_LIGHT_RADIUS := 165.0
const CAMPFIRE_FUEL_BURN_RATE := 1.0

const PLAYER_MAX_HEALTH := 100.0
const PLAYER_MAX_HUNGER := 100.0
const PLAYER_MAX_STAMINA := 100.0
const PLAYER_MAX_REST := 100.0
const PLAYER_LOW_HUNGER := 25.0
const PLAYER_EXHAUSTED_REST := 20.0
const PLAYER_HUNGER_DECAY_RATE := 0.9
const PLAYER_REST_DECAY_RATE := 0.35
const PLAYER_RUNNING_REST_DECAY_RATE := 0.9
const PLAYER_RUNNING_STAMINA_DECAY_RATE := 18.0
const PLAYER_STARVATION_DAMAGE_PER_SECOND := 3.0
const PLAYER_HEALTH_REGEN_RATE := 0.45
const PLAYER_MEAT_NUTRITION := 32.0
const PLAYER_SLEEP_HUNGER_COST := 8.0
const PLAYER_SLEEP_HEALTH_RESTORE := 35.0
const PLAYER_LOW_HUNGER_SPEED_MULTIPLIER := 0.82
const PLAYER_EXHAUSTED_REST_SPEED_MULTIPLIER := 0.85
const PLAYER_BASE_STAMINA_REGEN := 16.0
const PLAYER_LOW_HUNGER_STAMINA_REGEN_MULTIPLIER := 0.45
const PLAYER_EXHAUSTED_REST_STAMINA_REGEN_MULTIPLIER := 0.55

const NIGHT_DANGER_MULTIPLIER := 1.2
const ADAPTATION_DEBUG_GROWTH := 0.05
const ADAPTATION_TRAP_AWARENESS_GROWTH := 0.15
const ADAPTATION_FIRE_FEAR_DELTA := -0.10
const ADAPTATION_STALK_TENDENCY_GROWTH := 0.10
const ADAPTATION_PLAYER_AGGRESSION_GROWTH := 0.10
const ADAPTATION_PACK_COORDINATION_GROWTH := 0.10
const ADAPTATION_WALL_CURIOSITY_GROWTH := 0.10

const SPEAR_ATTACK_COOLDOWN := 0.0
const TRAP_DAMAGE := 120.0
const TRAP_EFFECT_DURATION := 0.0

const DEBUG_PLAYER_DAMAGE_AMOUNT := 25.0
const DEBUG_PLAYER_HEAL_AMOUNT := 25.0
const DEBUG_PLAYER_HUNGER_ENERGY_AMOUNT := 25.0
