extends RefCounted
class_name GameBalance

const TORCH_DURATION_SECONDS := 45.0
const TORCH_SAFE_RADIUS := 96.0
const TORCH_DETECTION_RANGE_MULTIPLIER := 0.65
const TORCH_AGGRESSION_MULTIPLIER := 0.7
const TORCH_CLOSE_CHASE_RANGE_MULTIPLIER := 0.65
const TORCH_ATTACK_COOLDOWN_MULTIPLIER := 1.5
const TORCH_FLEE_SPEED_MULTIPLIER := 0.85
const TORCH_LIGHT_RADIUS := 105.0
const TORCH_LIGHT_INTENSITY := 0.7
